### ISSUE TITLE
The application “Gatsby Desktop” can’t be opened. - on mac

### ISSUE THREAD

**Issue by i001962** [gatsbyjs/desktop#41]
After downloading Gatsby-Desktop-0.0.2-mac.zip and unzipping it, the following error message occurs trying to run the app: The application “Gatsby Desktop” can’t be opened. 

The dmg version launched without issue.
Good stuff. 

Where's the best place to log some usability suggestion?

**Comment by ascorbic** [comment]
Hi. Thanks. I'd stick to testing the .dmg releases, as they're the ones that are signed correctly. Feel free to post suggestions etc as issues here.
